version: '3'

services: 
    db:
        build: ./db
        ports:
            - "3307:3306"
    web:
        build: ./nodejs-backend
        ports:
            - "5000:5000"
        depends_on:
            - db
        restart: on-failure
        volumes:
            - ./nodejs-backend/:/app
            
    webfrontend:
        build: ./angular-frontend
        ports:
            - "8088:4200"